package junstech.dao;

import java.util.List;
import junstech.model.Criteria;

public interface CriteriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table criteria
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table criteria
     *
     * @mbggenerated
     */
    int insert(Criteria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table criteria
     *
     * @mbggenerated
     */
    Criteria selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table criteria
     *
     * @mbggenerated
     */
    List<Criteria> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table criteria
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Criteria record);
}