package junstech.dao;

import java.util.List;
import java.util.Map;

import junstech.model.Financetype;
import junstech.model.Paymentaccount;

public interface PaymentaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentaccount
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentaccount
     *
     * @mbggenerated
     */
    int insert(Paymentaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentaccount
     *
     * @mbggenerated
     */
    Paymentaccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentaccount
     *
     * @mbggenerated
     */
    List<Paymentaccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paymentaccount
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Paymentaccount record);
    
    List<Paymentaccount> selectByPage(Map<String, Object> map);
    
    Paymentaccount selectByName(String name);
}