package junstech.dao;

import java.util.List;
import junstech.model.Salesub;

public interface SalesubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesub
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesub
     *
     * @mbggenerated
     */
    int insert(Salesub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesub
     *
     * @mbggenerated
     */
    Salesub selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesub
     *
     * @mbggenerated
     */
    List<Salesub> selectAll();

    List<Salesub> selectBySaleId(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salesub
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Salesub record);
}