package junstech.dao;

import java.util.List;
import java.util.Map;

import junstech.model.Sale;

public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated
     */
    int insert(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated
     */
    Sale selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated
     */
    List<Sale> selectAll();

    List<Sale> selectByPage(Map<String, Object> map);
    
    List<Sale> selectByStatus(String status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sale record);
}