package junstech.model;

public class Paymentaccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentaccount.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paymentaccount.payaccount
     *
     * @mbggenerated
     */
    private String payaccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentaccount.id
     *
     * @return the value of paymentaccount.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentaccount.id
     *
     * @param id the value for paymentaccount.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paymentaccount.payaccount
     *
     * @return the value of paymentaccount.payaccount
     *
     * @mbggenerated
     */
    public String getPayaccount() {
        return payaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paymentaccount.payaccount
     *
     * @param payaccount the value for paymentaccount.payaccount
     *
     * @mbggenerated
     */
    public void setPayaccount(String payaccount) {
        this.payaccount = payaccount == null ? null : payaccount.trim();
    }
}