package junstech.model;

import java.util.List;

public class Privilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.key
     *
     * @mbggenerated
     */
    private Long key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.programName
     *
     * @mbggenerated
     */
    private int programid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilege.privilege
     *
     * @mbggenerated
     */
    private String privilege;

    private Criteria criteria;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.key
     *
     * @return the value of privilege.key
     *
     * @mbggenerated
     */
    public Long getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.key
     *
     * @param key the value for privilege.key
     *
     * @mbggenerated
     */
    public void setKey(Long key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.id
     *
     * @return the value of privilege.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.id
     *
     * @param id the value for privilege.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.programName
     *
     * @return the value of privilege.programName
     *
     * @mbggenerated
     */
    public int getProgramid() {
        return programid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.programName
     *
     * @param programname the value for privilege.programName
     *
     * @mbggenerated
     */
    public void setProgramid(int programid) {
        this.programid = programid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilege.privilege
     *
     * @return the value of privilege.privilege
     *
     * @mbggenerated
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilege.privilege
     *
     * @param privilege the value for privilege.privilege
     *
     * @mbggenerated
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege == null ? null : privilege.trim();
    }  
    
    public Criteria getCriteria() {
		return criteria;
	}

	public void setCriterias(Criteria criteria) {
		this.criteria = criteria;
	}

	public Privilege() {
	
	}
    
	public Privilege(int programid, Criteria criteria) {
		super();
		this.programid = programid;
		this.criteria = criteria;
	}

	public Privilege(Long id, int programid, String privilege) {
		super();
		this.id = id;
		this.programid = programid;
		this.privilege = privilege;
	}

	@Override
	public String toString() {
		return "Privilege [key=" + key + ", id=" + id + ", programid=" + programid + ", privilege=" + privilege + "]";
	}
    
    
}