package junstech.model;

import java.util.Date;

public class Purchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchaseid
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchasename
     *
     * @mbggenerated
     */
    private String purchasename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.goodid
     *
     * @mbggenerated
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.goodqty
     *
     * @mbggenerated
     */
    private Long goodqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.goodspec
     *
     * @mbggenerated
     */
    private String goodspec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.userid
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchasedate
     *
     * @mbggenerated
     */
    private Date purchasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.note
     *
     * @mbggenerated
     */
    private String note;
    
    private String status;

    private Good good;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchaseid
     *
     * @return the value of purchase.purchaseid
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchaseid
     *
     * @param purchaseid the value for purchase.purchaseid
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchasename
     *
     * @return the value of purchase.purchasename
     *
     * @mbggenerated
     */
    public String getPurchasename() {
        return purchasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchasename
     *
     * @param purchasename the value for purchase.purchasename
     *
     * @mbggenerated
     */
    public void setPurchasename(String purchasename) {
        this.purchasename = purchasename == null ? null : purchasename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.goodid
     *
     * @return the value of purchase.goodid
     *
     * @mbggenerated
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.goodid
     *
     * @param goodid the value for purchase.goodid
     *
     * @mbggenerated
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.goodqty
     *
     * @return the value of purchase.goodqty
     *
     * @mbggenerated
     */
    public Long getGoodqty() {
        return goodqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.goodqty
     *
     * @param goodqty the value for purchase.goodqty
     *
     * @mbggenerated
     */
    public void setGoodqty(Long goodqty) {
        this.goodqty = goodqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.goodspec
     *
     * @return the value of purchase.goodspec
     *
     * @mbggenerated
     */
    public String getGoodspec() {
        return goodspec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.goodspec
     *
     * @param goodspec the value for purchase.goodspec
     *
     * @mbggenerated
     */
    public void setGoodspec(String goodspec) {
        this.goodspec = goodspec == null ? null : goodspec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.price
     *
     * @return the value of purchase.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.price
     *
     * @param price the value for purchase.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.userid
     *
     * @return the value of purchase.userid
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.userid
     *
     * @param userid the value for purchase.userid
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchasedate
     *
     * @return the value of purchase.purchasedate
     *
     * @mbggenerated
     */
    public Date getPurchasedate() {
        return purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchasedate
     *
     * @param purchasedate the value for purchase.purchasedate
     *
     * @mbggenerated
     */
    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.note
     *
     * @return the value of purchase.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.note
     *
     * @param note the value for purchase.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
    
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Good getGood() {
		return good;
	}

	public void setGood(Good good) {
		this.good = good;
	}
    
    
}