package junstech.model;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.reporttime
     *
     * @mbggenerated
     */
    private String reporttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.reporttime
     *
     * @return the value of report.reporttime
     *
     * @mbggenerated
     */
    public String getReporttime() {
        return reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.reporttime
     *
     * @param reporttime the value for report.reporttime
     *
     * @mbggenerated
     */
    public void setReporttime(String reporttime) {
        this.reporttime = reporttime == null ? null : reporttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.path
     *
     * @return the value of report.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.path
     *
     * @param path the value for report.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}