package junstech.model;

public class Financereceivable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financereceivable.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financereceivable.saleid
     *
     * @mbggenerated
     */
    private Long saleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financereceivable.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financereceivable.companyid
     *
     * @mbggenerated
     */
    private Long companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financereceivable.totalamount
     *
     * @mbggenerated
     */
    private Double totalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financereceivable.nowpay
     *
     * @mbggenerated
     */
    private Double nowpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financereceivable.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financereceivable.id
     *
     * @return the value of financereceivable.id
     *
     * @mbggenerated
     */
    
    private Customer customer;
    
    public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financereceivable.id
     *
     * @param id the value for financereceivable.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financereceivable.saleid
     *
     * @return the value of financereceivable.saleid
     *
     * @mbggenerated
     */
    public Long getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financereceivable.saleid
     *
     * @param saleid the value for financereceivable.saleid
     *
     * @mbggenerated
     */
    public void setSaleid(Long saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financereceivable.type
     *
     * @return the value of financereceivable.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financereceivable.type
     *
     * @param type the value for financereceivable.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financereceivable.companyid
     *
     * @return the value of financereceivable.companyid
     *
     * @mbggenerated
     */
    public Long getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financereceivable.companyid
     *
     * @param companyid the value for financereceivable.companyid
     *
     * @mbggenerated
     */
    public void setCompanyid(Long companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financereceivable.totalamount
     *
     * @return the value of financereceivable.totalamount
     *
     * @mbggenerated
     */
    public Double getTotalamount() {
        return totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financereceivable.totalamount
     *
     * @param totalamount the value for financereceivable.totalamount
     *
     * @mbggenerated
     */
    public void setTotalamount(Double totalamount) {
        this.totalamount = totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financereceivable.nowpay
     *
     * @return the value of financereceivable.nowpay
     *
     * @mbggenerated
     */
    public Double getNowpay() {
        return nowpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financereceivable.nowpay
     *
     * @param nowpay the value for financereceivable.nowpay
     *
     * @mbggenerated
     */
    public void setNowpay(Double nowpay) {
        this.nowpay = nowpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financereceivable.note
     *
     * @return the value of financereceivable.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financereceivable.note
     *
     * @param note the value for financereceivable.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}