package junstech.model;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.goodname
     *
     * @mbggenerated
     */
    private String goodname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ID
     *
     * @return the value of product.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ID
     *
     * @param id the value for product.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.goodname
     *
     * @return the value of product.goodname
     *
     * @mbggenerated
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.goodname
     *
     * @param goodname the value for product.goodname
     *
     * @mbggenerated
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }
}