package junstech.dao;

import java.util.List;
import java.util.Map;

import junstech.model.Financereceivable;
import junstech.model.Inventory;

public interface FinancereceivableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financereceivable
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financereceivable
     *
     * @mbggenerated
     */
    int insert(Financereceivable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financereceivable
     *
     * @mbggenerated
     */
    Financereceivable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financereceivable
     *
     * @mbggenerated
     */
    List<Financereceivable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financereceivable
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Financereceivable record);
    
    List<Financereceivable> selectByPage(Map<String, Object> map);
    
    Financereceivable selectSummary(Map<String, Object> map);
    
    List<Financereceivable> selectSummaryByPage(Map<String, Object> map);
    
    List<Financereceivable> selectAllByFields(Map<String, Object> map);
}