package junstech.dao;

import java.util.List;
import java.util.Map;

import junstech.model.Good;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer goodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    Good selectByPrimaryKey(Integer goodid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    List<Good> selectAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    List<Good> selectByPage(Map<String, Object> map);
    
    List<Good> selectAllGoods();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Good record);
}