package junstech.dao;

import java.util.List;
import java.util.Map;

import junstech.model.Inventory;

public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    int deleteByActionId(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    int insert(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    Inventory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    List<Inventory> selectAll();

    List<Inventory> selectForVerifyBatch();
    
    List<Inventory> selectByPage(Map<String, Object> map);
    
    Inventory selectSummary(Map<String, Object> map);
    
    List<Inventory> selectSummaryByPage(Map<String, Object> map);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Inventory record);
}