package junstech.dao;

import java.util.List;
import java.util.Map;

import junstech.model.Ledger;
import junstech.model.Ledger;

public interface LedgerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger
     *
     * @mbggenerated
     */
    int insert(Ledger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger
     *
     * @mbggenerated
     */
    Ledger selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger
     *
     * @mbggenerated
     */
    List<Ledger> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ledger
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ledger record);

    List<Ledger> selectForVerifyBatch();
    
    List<Ledger> selectByPage(Map<String, Object> map);
    
    Ledger selectSummary(Map<String, Object> map);
    
    List<Ledger> selectSummaryByPage(Map<String, Object> map);
    
    List<Ledger> selectByFields(Map<String, Object> map);
    
    List<Ledger> selectTotalByFields(Map<String, Object> map);
}