package junstech.model;

public class Good {
	
	private Supplier supplier;
	
	private Product product;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.goodid
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.goodname
     *
     * @mbggenerated
     */
    private String goodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.goodsortid
     *
     * @mbggenerated
     */
    private Integer goodsortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.supplierid
     *
     * @mbggenerated
     */
    private Integer supplierid;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.goodid
     *
     * @return the value of good.goodid
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.goodid
     *
     * @param goodid the value for good.goodid
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.goodname
     *
     * @return the value of good.goodname
     *
     * @mbggenerated
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.goodname
     *
     * @param goodname the value for good.goodname
     *
     * @mbggenerated
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.goodsortid
     *
     * @return the value of good.goodsortid
     *
     * @mbggenerated
     */
    public Integer getGoodsortid() {
        return goodsortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.goodsortid
     *
     * @param goodsortid the value for good.goodsortid
     *
     * @mbggenerated
     */
    public void setGoodsortid(Integer goodsortid) {
        this.goodsortid = goodsortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.supplierid
     *
     * @return the value of good.supplierid
     *
     * @mbggenerated
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.supplierid
     *
     * @param supplierid the value for good.supplierid
     *
     * @mbggenerated
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

	public Supplier getSupplier() {
		return supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
    
    
}