package junstech.model;

import java.util.Date;

public class Inventory {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.ID
	 *
	 * @mbggenerated
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.goodid
	 *
	 * @mbggenerated
	 */
	private Integer goodid;

	private Integer goodsortid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.status
	 *
	 * @mbggenerated
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.price
	 *
	 * @mbggenerated
	 */
	private Double price;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.inventoryqty
	 *
	 * @mbggenerated
	 */
	private Long inventoryqty;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.minreserves
	 *
	 * @mbggenerated
	 */
	private String actionid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.norreserves
	 *
	 * @mbggenerated
	 */
	private Date executedate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.type
	 *
	 * @mbggenerated
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column inventory.lastedittime
	 *
	 * @mbggenerated
	 */
	private Date lastedittime;

	private String proof;

	private Good good;

	private Product product;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.ID
	 *
	 * @return the value of inventory.ID
	 *
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.ID
	 *
	 * @param id
	 *            the value for inventory.ID
	 *
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.goodid
	 *
	 * @return the value of inventory.goodid
	 *
	 * @mbggenerated
	 */
	public Integer getGoodid() {
		return goodid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.goodid
	 *
	 * @param goodid
	 *            the value for inventory.goodid
	 *
	 * @mbggenerated
	 */
	public void setGoodid(Integer goodid) {
		this.goodid = goodid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.status
	 *
	 * @return the value of inventory.status
	 *
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.status
	 *
	 * @param status
	 *            the value for inventory.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.price
	 *
	 * @return the value of inventory.price
	 *
	 * @mbggenerated
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.price
	 *
	 * @param price
	 *            the value for inventory.price
	 *
	 * @mbggenerated
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.inventoryqty
	 *
	 * @return the value of inventory.inventoryqty
	 *
	 * @mbggenerated
	 */
	public Long getInventoryqty() {
		return inventoryqty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.inventoryqty
	 *
	 * @param inventoryqty
	 *            the value for inventory.inventoryqty
	 *
	 * @mbggenerated
	 */
	public void setInventoryqty(Long inventoryqty) {
		this.inventoryqty = inventoryqty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.minreserves
	 *
	 * @return the value of inventory.minreserves
	 *
	 * @mbggenerated
	 */
	public String getActionid() {
		return actionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.minreserves
	 *
	 * @param minreserves
	 *            the value for inventory.minreserves
	 *
	 * @mbggenerated
	 */
	public void setActionid(String actionid) {
		this.actionid = actionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.norreserves
	 *
	 * @return the value of inventory.norreserves
	 *
	 * @mbggenerated
	 */
	public Date getExecutedate() {
		return executedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.norreserves
	 *
	 * @param norreserves
	 *            the value for inventory.norreserves
	 *
	 * @mbggenerated
	 */
	public void setExecutedate(Date executedate) {
		this.executedate = executedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.type
	 *
	 * @return the value of inventory.type
	 *
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.type
	 *
	 * @param type
	 *            the value for inventory.type
	 *
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column inventory.lastedittime
	 *
	 * @return the value of inventory.lastedittime
	 *
	 * @mbggenerated
	 */
	public Date getLastedittime() {
		return lastedittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column inventory.lastedittime
	 *
	 * @param lastedittime
	 *            the value for inventory.lastedittime
	 *
	 * @mbggenerated
	 */
	public void setLastedittime(Date lastedittime) {
		this.lastedittime = lastedittime;
	}

	public String getProof() {
		return proof;
	}

	public void setProof(String proof) {
		this.proof = proof;
	}

	public Integer getGoodsortid() {
		return goodsortid;
	}

	public void setGoodsortid(Integer goodsortid) {
		this.goodsortid = goodsortid;
	}

	public Good getGood() {
		return good;
	}

	public void setGood(Good good) {
		this.good = good;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}