package junstech.model;

import java.util.Date;

public class Ledger {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.receiveid
     *
     * @mbggenerated
     */
    private Long receiveid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.companytype
     *
     * @mbggenerated
     */
    private String companytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.financetype
     *
     * @mbggenerated
     */
    private Integer financetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.companyid
     *
     * @mbggenerated
     */
    private Long companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.payman
     *
     * @mbggenerated
     */
    private String payman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.paydate
     *
     * @mbggenerated
     */
    private Date paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ledger.proof
     *
     * @mbggenerated
     */
    private String proof;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.id
     *
     * @return the value of ledger.id
     *
     * @mbggenerated
     */
    
    private Supplier supplier;
    
    private Financetype financetypeinfo;
    
    private Customer customer;
    
    
    
    public Supplier getSupplier() {
		return supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public Financetype getFinancetypeinfo() {
		return financetypeinfo;
	}

	public void setFinancetypeinfo(Financetype financetypeinfo) {
		this.financetypeinfo = financetypeinfo;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.id
     *
     * @param id the value for ledger.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.receiveid
     *
     * @return the value of ledger.receiveid
     *
     * @mbggenerated
     */
    public Long getReceiveid() {
        return receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.receiveid
     *
     * @param receiveid the value for ledger.receiveid
     *
     * @mbggenerated
     */
    public void setReceiveid(Long receiveid) {
        this.receiveid = receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.companytype
     *
     * @return the value of ledger.companytype
     *
     * @mbggenerated
     */
    public String getCompanytype() {
        return companytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.companytype
     *
     * @param companytype the value for ledger.companytype
     *
     * @mbggenerated
     */
    public void setCompanytype(String companytype) {
        this.companytype = companytype == null ? null : companytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.financetype
     *
     * @return the value of ledger.financetype
     *
     * @mbggenerated
     */
    public Integer getFinancetype() {
        return financetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.financetype
     *
     * @param financetype the value for ledger.financetype
     *
     * @mbggenerated
     */
    public void setFinancetype(Integer financetype) {
        this.financetype = financetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.companyid
     *
     * @return the value of ledger.companyid
     *
     * @mbggenerated
     */
    public Long getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.companyid
     *
     * @param companyid the value for ledger.companyid
     *
     * @mbggenerated
     */
    public void setCompanyid(Long companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.payman
     *
     * @return the value of ledger.payman
     *
     * @mbggenerated
     */
    public String getPayman() {
        return payman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.payman
     *
     * @param payman the value for ledger.payman
     *
     * @mbggenerated
     */
    public void setPayman(String payman) {
        this.payman = payman == null ? null : payman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.paydate
     *
     * @return the value of ledger.paydate
     *
     * @mbggenerated
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.paydate
     *
     * @param paydate the value for ledger.paydate
     *
     * @mbggenerated
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.amount
     *
     * @return the value of ledger.amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.amount
     *
     * @param amount the value for ledger.amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.note
     *
     * @return the value of ledger.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.note
     *
     * @param note the value for ledger.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ledger.proof
     *
     * @return the value of ledger.proof
     *
     * @mbggenerated
     */
    public String getProof() {
        return proof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ledger.proof
     *
     * @param proof the value for ledger.proof
     *
     * @mbggenerated
     */
    public void setProof(String proof) {
        this.proof = proof;
    }
}