package junstech.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Salesub {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesub.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesub.saleid
     *
     * @mbggenerated
     */
    private Long saleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesub.goodid
     *
     * @mbggenerated
     */
    private Integer goodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesub.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesub.goodqty
     *
     * @mbggenerated
     */
    private Long goodqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesub.opertime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd") 
    private Date opertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salesub.verification
     *
     * @mbggenerated
     */
    private String verification;

    private Product product;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesub.ID
     *
     * @return the value of salesub.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesub.ID
     *
     * @param id the value for salesub.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesub.saleid
     *
     * @return the value of salesub.saleid
     *
     * @mbggenerated
     */
    public Long getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesub.saleid
     *
     * @param saleid the value for salesub.saleid
     *
     * @mbggenerated
     */
    public void setSaleid(Long saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesub.goodid
     *
     * @return the value of salesub.goodid
     *
     * @mbggenerated
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesub.goodid
     *
     * @param goodid the value for salesub.goodid
     *
     * @mbggenerated
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesub.price
     *
     * @return the value of salesub.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesub.price
     *
     * @param price the value for salesub.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesub.goodqty
     *
     * @return the value of salesub.goodqty
     *
     * @mbggenerated
     */
    public Long getGoodqty() {
        return goodqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesub.goodqty
     *
     * @param goodqty the value for salesub.goodqty
     *
     * @mbggenerated
     */
    public void setGoodqty(Long goodqty) {
        this.goodqty = goodqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesub.opertime
     *
     * @return the value of salesub.opertime
     *
     * @mbggenerated
     */
    public Date getOpertime() {
        return opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesub.opertime
     *
     * @param opertime the value for salesub.opertime
     *
     * @mbggenerated
     */
    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salesub.verification
     *
     * @return the value of salesub.verification
     *
     * @mbggenerated
     */
    public String getVerification() {
        return verification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salesub.verification
     *
     * @param verification the value for salesub.verification
     *
     * @mbggenerated
     */
    public void setVerification(String verification) {
        this.verification = verification == null ? null : verification.trim();
    }

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
    
    
}