package junstech.model;

import java.util.Date;
import java.util.List;

public class Sale {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sale.ID
	 *
	 * @mbggenerated
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sale.salemanid
	 *
	 * @mbggenerated
	 */
	private Long salemanid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sale.customerid
	 *
	 * @mbggenerated
	 */
	private Long customerid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sale.saletime
	 *
	 * @mbggenerated
	 */
	private Date saletime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sale.operman
	 *
	 * @mbggenerated
	 */
	private Long operman;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sale.total
	 *
	 * @mbggenerated
	 */
	private Double total;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sale.status
	 *
	 * @mbggenerated
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sale.note
	 *
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sale.ID
	 *
	 * @return the value of sale.ID
	 *
	 * @mbggenerated
	 */

	private List<Salesub> salesubs;

	private Customer customer;

	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sale.ID
	 *
	 * @param id
	 *            the value for sale.ID
	 *
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sale.salemanid
	 *
	 * @return the value of sale.salemanid
	 *
	 * @mbggenerated
	 */
	public Long getSalemanid() {
		return salemanid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sale.salemanid
	 *
	 * @param salemanid
	 *            the value for sale.salemanid
	 *
	 * @mbggenerated
	 */
	public void setSalemanid(Long salemanid) {
		this.salemanid = salemanid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sale.customerid
	 *
	 * @return the value of sale.customerid
	 *
	 * @mbggenerated
	 */
	public Long getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sale.customerid
	 *
	 * @param customerid
	 *            the value for sale.customerid
	 *
	 * @mbggenerated
	 */
	public void setCustomerid(Long customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sale.saletime
	 *
	 * @return the value of sale.saletime
	 *
	 * @mbggenerated
	 */
	public Date getSaletime() {
		return saletime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sale.saletime
	 *
	 * @param saletime
	 *            the value for sale.saletime
	 *
	 * @mbggenerated
	 */
	public void setSaletime(Date saletime) {
		this.saletime = saletime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sale.operman
	 *
	 * @return the value of sale.operman
	 *
	 * @mbggenerated
	 */
	public Long getOperman() {
		return operman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sale.operman
	 *
	 * @param operman
	 *            the value for sale.operman
	 *
	 * @mbggenerated
	 */
	public void setOperman(Long operman) {
		this.operman = operman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sale.total
	 *
	 * @return the value of sale.total
	 *
	 * @mbggenerated
	 */
	public Double getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sale.total
	 *
	 * @param total
	 *            the value for sale.total
	 *
	 * @mbggenerated
	 */
	public void setTotal(Double total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sale.status
	 *
	 * @return the value of sale.status
	 *
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sale.status
	 *
	 * @param status
	 *            the value for sale.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sale.note
	 *
	 * @return the value of sale.note
	 *
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sale.note
	 *
	 * @param note
	 *            the value for sale.note
	 *
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	public List<Salesub> getSalesubs() {
		return salesubs;
	}

	public void setSalesubs(List<Salesub> salesubs) {
		this.salesubs = salesubs;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

}